/* eslint-disable no-unused-vars */
export enum Components {
  A = 'A',
  COL = 'COL',
  EMBED = 'EMBED',
  H6 = 'H6',
  MAIN = 'MAIN',
  PROGRESS = 'PROGRESS',
  TBODY = 'TBODY',
  ADDRESS = 'ADDRESS',
  COLGROUP = 'COLGROUP',
  FIELDSET = 'FIELDSET',
  HEADER = 'HEADER',
  MAP = 'MAP',
  Q = 'Q',
  TD = 'TD',
  AREA = 'AREA',
  DD = 'DD',
  FIGCAPTION = 'FIGCAPTION',
  HGROUP = 'HGROUP',
  MARK = 'MARK',
  SECTION = 'SECTION',
  TEXTAREA = 'TEXTAREA',
  DEL = 'DEL',
  ARTICLE = 'ARTICLE',
  FIGURE = 'FIGURE',
  HR = 'HR',
  MENU = 'MENU',
  SELECT = 'SELECT',
  TFOOT = 'TFOOT',
  ASIDE = 'ASIDE',
  DETAILS = 'DETAILS',
  FOOTER = 'FOOTER',
  I = 'I',
  NAV = 'NAV',
  SMALL = 'SMALL',
  TH = 'TH',
  B = 'B',
  DFN = 'DFN',
  FORM = 'FORM',
  OL = 'OL',
  SPAN = 'SPAN',
  THEAD = 'THEAD',
  BLOCKQUOTE = 'BLOCKQUOTE',
  DIALOG = 'DIALOG',
  H1 = 'H1',
  INPUT = 'INPUT',
  OPTGROUP = 'OPTGROUP',
  STRONG = 'STRONG',
  TR = 'TR',
  BR = 'BR',
  DIV = 'DIV',
  H2 = 'H2',
  INS = 'INS',
  OPTION = 'OPTION',
  SUB = 'SUB',
  U = 'U',
  BUTTON = 'BUTTON',
  DL = 'DL',
  H3 = 'H3',
  LABEL = 'LABEL',
  P = 'P',
  SUMMARY = 'SUMMARY',
  UL = 'UL',
  CANVAS = 'CANVAS',
  DT = 'DT',
  H4 = 'H4',
  LEGEND = 'LEGEND',
  PICTURE = 'PICTURE',
  SUP = 'SUP',
  CAPTION = 'CAPTION',
  EM = 'EM',
  H5 = 'H5',
  LI = 'LI',
  PRE = 'PRE',
  TABLE = 'TABLE',

  // Molecules

  CARD_BODY = 'CARD_BODY',
  CARD_FOOTER = 'CARD_FOOTER',
  CARD_HEADER = 'CARD_HEADER',
  INPUT_GROUP = 'INPUT_GROUP',

  // Organisms

  CARD = 'CARD',
  // Core End

  // components Start
  // Atoms
  BOX = 'BOX',
  Row = 'Row',
  CONTAINER = 'CONTAINER',
  // Molecules

  // components End
}

export type Component = keyof typeof Components;
